spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
      show_sql: true
  thymeleaf:
    cache: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    include:
      - db
      - jwt
      - kakao

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org.springframework.security: trace
    com.ddudu.todo: debug